title: Shattered Oak Brewing
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0
  brandStrength: 1
  lightness: 0
  brandColors:
    - '#181C28'
    - '#FFEEE0'
    - '#AD75BD'
    - '#915B31'
    - '#C7C691'
  rhythmicContrast: 0
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: Shattered Oak
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.6953405
layout_spectrum: 0.4193548
