layout_spectrum: 0.4659498
color:
  saturation: 0.3978495
  lightness: 0.8315412
  brandStrength: 1
  brandColors:
    - '#181C28'
    - '#FFEEE0'
    - '#AD75BD'
    - '#915B31'
    - '#C7C691'
  rhythmicContrast: 0.374552
typography_spectrum: 0.6953405
name: Shattered Oak
