name: Shattered Oak
favicon: null
layout_spectrum: 0.90897
typography_spectrum: 0.15875
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Shattered Oak Brewing
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#181C28'
    - '#FFEEE0'
    - '#AD75BD'
    - '#915B31'
    - '#C7C691'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
